### ISSUE TITLE
TLD dropdown selection of [other] appends herokuapp.com

### ISSUE THREAD

**Issue by rahim** [rahim/nightwear#38]
I've not observed this but there's at least one report of this in #28 

> @arakon:
> Also, if I select an "other" URL (self-hosted), it automatically attaches the herokuapp.com anyways, making the URL invalid.

It may get addressed as a side affect of changes in https://github.com/rahim/nightwear/pull/37

**Comment by Loquacity** [comment]
This image is of the setting I put in, with the API key, selecting `other`. This is saved effectively, and I'm returned to the face:
![image](https://user-images.githubusercontent.com/3914967/203671865-32ab7641-d17a-4623-b4c7-c6f82b23dfb8.png)

Going back in to edit settings for the complication, and you can see the setting has changed to `herokuapp.com` and appended the herokuapp to the URL I entered:
![image](https://user-images.githubusercontent.com/3914967/203671949-9c97cd9b-68b3-49df-a087-2caa307f1fc4.png)

**Comment by rahim** [comment]
Thanks @Loquacity, as soon as I get a chance I'll have a go at reproducing and fixing, that may be a few days though.

**Comment by stijnbrouwers** [comment]
+1 I also seem to be facing this issue

**Comment by rahim** [comment]
@Loquacity, @stijnbrouwers I've pushed a beta release that I hope should address this. To opt in to the beta stream please follow [Google's instructions here](https://support.google.com/googleplay/answer/7003180). Please let me know how you get on and I'll promote to general release.

**Comment by rahim** [comment]
If you need it, the NightWear play store URL is https://play.google.com/store/apps/details?id=im.rah.nightwear

**Comment by rahim** [comment]
Better still from a web browser a direct link to join the beta - https://play.google.com/apps/testing/im.rah.nightwear

**Comment by Loquacity** [comment]
That is amazing, thank you! 💖 

And it's working well, too:

![image](https://user-images.githubusercontent.com/3914967/204669672-b7c0f12b-ceb1-4903-b50d-febde7b92b78.png)

**Comment by rahim** [comment]
@Loquacity Excellent news, glad it's useful!
